export const config = {
  PASSING_SCORE: 0.75,
  MAX_ATTEMPTS: 3,
  AUTO_ADVANCE_DELAY: 1500,
  FEEDBACK_DELAY: 800,
  RECORD_MAX_DURATION: 5000,
  SELF_REPORT_SCORE_YES: 0.85,
  SELF_REPORT_SCORE_NO: 0.1,
  TOTAL_LESSONS: 10,
};
